language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: KNnbqmQvIlxIYqxdhtJRQRe8zzg8FYYm83Uj1eE+HBbDxdupfbb42yL0CyDZ6CQC4LCJmrbBjcm5ztK4DmQWyRHWs8VkWbQUEmQusVmlhUENxCI96G+Ixr0/3EQtowfTl/RVrd4weQJ8Oz3aGF/ggcnRILOmR2yTd+8KW20i7IsglIYKQWzw5o9DyC7ULAMVAE/I7bS4PhoEyEGJmD1B+2ldM0BtWW9p3hphDsjqREYbY56oh0WQraFw40tFDTsln/k2gQ6TKuA8vOuDZxGUlZEbJVj+iNOzE9FxnhLG1tMRUqNWFb+L5/uq2r2cAgvG6oM9CofCCk3pTJEh+pS79x7hNGy93+6D8HHD/PYt8sGJHhUGisN5TTVK0i3larLIFHLZDmnHFRSZ3wiqztyo0UQcfVfO5bf7VlDqFb3n3Tf0wJxJZAMUX38CgL3VtEs66+Gjo6GkPapVOfIRvBFJSXxLQSMT7ybphx0BV197+lMgJ3il1Vp6OFmNdYsONP/ASMcALK0vXS2kxJMOrznydmEfykfZSSKh+TUUzkqmaVM5FsnkG6b77AYu+7gACvHwf/BlqV9JCsG1Cn+nfKUzFIJKjvWlDDfPbHlroUwqBttf32dSCjkJTLRChnYmoonYSxREytScYaxzduZ5ncUx+7PGuAuRZTh6Y89JRuKCaUs=
  on:
    branch: develop
